# Generated by Django 2.2 on 2019-06-01 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_client', models.BooleanField()),
                ('client_reminded', models.BooleanField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment2client', to=settings.AUTH_USER_MODEL)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment2consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossary', models.CharField(default='help-guide', max_length=20)),
                ('content_en', models.TextField()),
                ('content_ar', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('pic_url', models.CharField(max_length=255)),
                ('profile_en', models.TextField()),
                ('profile_ar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('made', models.CharField(max_length=3)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpGuideSnippets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.CharField(max_length=255)),
                ('content_ar', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_HelpGuide_Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('snippet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.HelpGuideSnippets')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('prescribtion_id', models.IntegerField()),
                ('notes', models.TextField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Appointments')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session2client', to=settings.AUTH_USER_MODEL)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session2consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionDashboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Sessions')),
            ],
        ),
        migrations.CreateModel(
            name='Prescribtions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed', models.BooleanField()),
                ('shipped', models.BooleanField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribtion2packer', to=settings.AUTH_USER_MODEL)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Sessions')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribtion2shipper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribtionDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Drugs')),
                ('prescribtion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Prescribtions')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=10)),
                ('attachment_type', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message2reciever', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message2sender', to=settings.AUTH_USER_MODEL)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Sessions')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('taxonomy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('released', models.BooleanField()),
                ('released_date', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon2client', to=settings.AUTH_USER_MODEL)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon2consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.TextField()),
                ('consultation_anonymous', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reply', models.TextField()),
                ('reply_anonymous', models.TextField()),
                ('reply_date', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation2client', to=settings.AUTH_USER_MODEL)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation2consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant_ClientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('summary', models.TextField()),
                ('summary_backup', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file2client', to=settings.AUTH_USER_MODEL)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file2consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='taxonomy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Taxonomy'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='coupon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Coupons'),
        ),
    ]
