# Generated by Django 2.2 on 2019-06-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False # <<<< THIS LINE
    
    dependencies = [
        ('exeerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
    ]
