# Generated by Django 2.2 on 2019-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0002_auto_20190602_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title_ar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
