# Generated by Django 2.2 on 2019-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0003_auto_20190602_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='session_preice_usd',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='session_price_sp',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
