# Generated by Django 2.2 on 2019-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0007_auto_20190603_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='session_preice_usd',
            new_name='session_price_usd',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='picture',
            field=models.FileField(default=None, upload_to='uploads/consultants-pics/'),
            preserve_default=False,
        ),
    ]
