# Generated by Django 2.2 on 2019-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0009_consultantprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='picture',
            field=models.FileField(null=True, upload_to='uploads/consultants-pics/'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='session_price_sp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='session_price_usd',
            field=models.IntegerField(null=True),
        ),
    ]
