# Generated by Django 2.2 on 2019-06-05 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0010_auto_20190605_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
