# Generated by Django 2.2 on 2019-06-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exeerapp', '0011_auto_20190605_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='consultant_id',
        ),
        migrations.RemoveField(
            model_name='consultant_clientfile',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='consultant_clientfile',
            name='consultant_id',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='consultant_id',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='consultant_id',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='taxonomy_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='prescribtiondrugs',
            name='drug_id',
        ),
        migrations.RemoveField(
            model_name='prescribtiondrugs',
            name='prescribtion_id',
        ),
        migrations.RemoveField(
            model_name='prescribtions',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='consultant_id',
        ),
        migrations.RemoveField(
            model_name='user_helpguide_taxonomy',
            name='snippet_id',
        ),
        migrations.RemoveField(
            model_name='user_helpguide_taxonomy',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appointments',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment2client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='consultant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment2consultant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant_clientfile',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file2client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant_clientfile',
            name='consultant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file2consultant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultations',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation2client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultations',
            name='consultant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation2consultant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coupon2client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='consultant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coupon2consultant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='taxonomy',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Taxonomy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message2reciever', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescribtiondrugs',
            name='drug',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Drugs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescribtiondrugs',
            name='prescribtion',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Prescribtions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescribtions',
            name='session',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Sessions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='appointment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Appointments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session2client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='consultant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session2consultant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_helpguide_taxonomy',
            name='snippet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exeerapp.HelpGuideSnippets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_helpguide_taxonomy',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='coupon_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Coupons'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='taxonomy_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helpguidesnippets',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Articles'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='session_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Sessions'),
        ),
        migrations.AlterField(
            model_name='prescribtions',
            name='packer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescribtion2packer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescribtions',
            name='shipper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescribtion2shipper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessiondashboards',
            name='session_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exeerapp.Sessions'),
        ),
    ]
