# Generated by Django 2.2 on 2019-06-10 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0012_auto_20190610_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultations',
            name='reply_date',
        ),
        migrations.AddField(
            model_name='consultations',
            name='client_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation2client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='consultant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation2consultant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='consultation_anonymous',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='reply',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='reply_anonymous',
            field=models.TextField(null=True),
        ),
    ]
