# Generated by Django 2.2 on 2019-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0013_auto_20190610_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
