# Generated by Django 2.2 on 2019-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeerapp', '0014_consultations_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='title',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='consultation',
            field=models.TextField(verbose_name='Original question'),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='consultation_anonymous',
            field=models.TextField(null=True, verbose_name='Anonymous question'),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='reply',
            field=models.TextField(null=True, verbose_name='Original answer'),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='reply_anonymous',
            field=models.TextField(null=True, verbose_name='Anonymous answer'),
        ),
    ]
